[playing_args]
play_with = dqn
play_using_white = True
using_endgame_database = False
n_playout = 50

[model_args]
checkpoint = ../savedata/DQN_GruN1_epoch800_20260625_0851
name = DQN_GruN1
; # cpu, cuda or mps
device = cuda
l2_const = 1e-5
n_steps = 1
use_gru = True

[training_args]
max_epoch = 10000
batch_size = 258
n_cores = 4
epochs = 40

learn_rate = 0.0007
gamma = 0.99
tau = 0.005
epsilon_start = 1
epsilon_end = 0.05
; # was 1000 in the one with fastest falling eps
epsilon_decay = 3000
buffer_size = 300000
starting_buffer_games = 1500
beta_start = 0.4
beta_frames = 10000

[evaluation]
# training eval
eval_freq = 100
n_eval_playout = 25
n_eval_games = 100
checkpoint_freq = 200
# vvv używane w run_test
n_test_playout = 100
n_test_games = 1000
