[playing_args]
play_with = dqn
play_using_white = True
using_endgame_database = True
n_playout = 100

[model_args]
;checkpoint = ../savedata/DQN_lap_epoch15000_20260406_0025
name = DQN_kap
; # cpu, cuda or mps
device = cpu
l2_const = 1e-5
n_steps = 4

[training_args]
max_epoch = 20000
batch_size = 256
n_cores = 4
epochs = 20

learn_rate = 0.0001
gamma = 0.99
tau = 0.005
epsilon_start = 1
epsilon_end = 0.02
; # was 1000 in the one with fastest falling eps
epsilon_decay = 5000
buffer_size = 300000
starting_buffer_games = 1500
beta_start = 0.4
beta_frames = 30000

[evaluation]
eval_freq = 200
n_eval_games = 100
n_test_playout = 100
n_test_games = 1000
checkpoint_freq = 500
