[playing_args]
play_with = dqn
play_using_white = True
using_endgame_database = True
n_playout = 50

[model_args]
#checkpoint = ../savedata/DQN_req_2_epoch600_20260531_2025
name = DQN_2
; # cpu, cuda or mps
device = cuda
l2_const = 3e-5
n_steps = 2
recursive_steps = 1

[training_args]
max_epoch = 4000
batch_size = 258
n_cores = 4
epochs = 40

learn_rate = 0.001
gamma = 0.99
tau = 0.005
epsilon_start = 1
epsilon_end = 0.05
; # was 1000 in the one with fastest falling eps
epsilon_decay = 3000
buffer_size = 300000
starting_buffer_games = 400
beta_start = 0.4
beta_frames = 10000

[evaluation]
# training eval
eval_freq = 100
n_eval_playout = 25
n_eval_games = 100
checkpoint_freq = 100
# vvv używane w run_test
n_test_playout = 100
n_test_games = 1000
